language: go

services:
  - docker

go:
  - 1.10.1

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

before_script:
  - go get -t ./...
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /godogs/ | tr "\n" " ")
  - go get github.com/golang/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get github.com/DATA-DOG/godog/cmd/godog

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go vet -v ./...
  - gocyclo -over 4 $(echo $GO_FILES)
  - golint -set_exit_status $(go list ./...)
  - cd godogs && godog && cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./build.sh
  - docker build -t falabellacr/imperium-server:t-${TRAVIS_BUILD_NUMBER} .
  - docker push falabellacr/imperium-server:t-${TRAVIS_BUILD_NUMBER}
